name: Health check

on:
  push:
    branches:
      - main
jobs: 
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-solitary-grass-3183.fly.dev/health
          max-attempts: 3
