name: hello world

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo hello world
        run: |
          echo "hello world"
      - name: Run date
        run: |
          date
      - name: Run ls
        run: |
          ls -l
